allowHosts:
  - "DrSprinto://main"
hostLabels:
  - pattern: "^http://127.0.0.1:5000"
    name: Local Server
  - pattern: "^http://localhost:5000"
    name: Local Server
  - pattern: "^https://(.+\\.)?sprinto\\.(com|in)"
    name: Sprinto
policyServer:
testHosts:
  # - url: "http://foo.bar.com"
  #   label: Display Value
